### ISSUE TITLE
Error in testing

### ISSUE THREAD

**Issue by Abhijitdas2048** [luuuyi/CBAM.PyTorch#8]
hi I ma getting this error while testing
Traceback (most recent call last):
  File "test.py", line 213, in <module>
    test_and_generate_result_round2('2','resnet50',416, True)
  File "test.py", line 133, in test_and_generate_result_round2
    my_model = resnet50.MyResNet50(model_ft)
NameError: name 'resnet50' is not defined

**Comment by ConredLin** [comment]
I also got the error, I can't find the resnet
